### ISSUE TITLE
Avoid usage of process.cwd()

### ISSUE THREAD

**Issue by mcollina** [yonathan06/fastify-now#1]
The usage of process.cwd() prevents to use this module to package routes in another module. This is common when using lerna (etc).

I would recommend accepting the folder as a parameter.

**Comment by yonathan06** [comment]
Thanks!
It uses `process.cwd()` only when no `routesFolder` parameter is provided.
You can see in the example I have in the main readme, that I use `path.join(__dirname, './routes')` as the `routesFolder`.
Maybe I should remove the default `routesFolder` parameter and throw an error if non provided.

**Comment by mcollina** [comment]
I would recommend it. It’s easy to mess up :(, even if it’s a nice dx.

**Comment by yonathan06** [comment]
https://github.com/yonathan06/fastify-now/commit/cc6dfc098176eb96b7a3bf78a5d377ac198792d6
