### ISSUE TITLE
How can I get the fastify instance inside a function handler?

### ISSUE THREAD

**Issue by barenko** [yonathan06/fastify-now#12]
I have the follow function in the `routes/index.js` file. How can I get the same fastify server instance that the fastify-now was registered?

```
module.exports.GET = async (req, res) => {
    await fastifyServer.db.connect();
    ...
    res.send({ hello: 'world' })
}
```

**Comment by mandaputtra** [comment]
You can use, `this`.  It will refer to Fastify instance.

**Comment by yonathan06** [comment]
@mandaputtra is right, but you will need to declare a function using the `function` keyword in order to have the right context bound to it.
```JavaSctipt
module.exports.GET = async function getWorld(req, res) {
    // this = fastify instance
    await this.db.connect();
    ...
 }
```
