### ISSUE TITLE
RouteGeneric types (reply typings)

### ISSUE THREAD

**Issue by mielp** [yonathan06/fastify-now#16]
Right now I use the following pattern to describe a route:

```ts
interface Post
  extends NowRequestHandler<{
    Body: MyRequestBody;
    Headers: MyRequestHeaders;
    Params: MyRequestParams;
    Querystring: MyRequestQuerystring;
  }> {}

// POST /path/to/this/route
export const POST: Post = async (request, reply): Promise<MyReply> => {
  return { something: "something" };
};

POST.opts = { /* options here */ };
```

I don't know yet how feasible that would be, but it would be pretty neat to have the `NowRequestHandler`'s `RequestGeneric` replaced by a `RouteGeneric` extending Fastify's `RouteGenericInterface` instead of `RequestGenericInterface`.

Maybe it should be a new `NowRouteHandler` interface?

This would make the following snippet work, which would allow a better separation of route interfaces and route definitions, and would be a bit easier to read in case the `MyReply` interface was embedded instead of imported from somewhere else.

```ts
interface Post
  extends NowRequestHandler<{ // or NowRouteHandler
    Body: MyRequestBody;
    Headers: MyRequestHeaders;
    Params: MyRequestParams;
    Querystring: MyRequestQuerystring;
    Reply: MyReply;
  }> {}

// POST /path/to/this/route
export const POST: Post = async (request, reply) => {
  return { something: "something" };
};

POST.opts = { /* options here */ };
```

What do you think?

**Comment by yonathan06** [comment]
Didn't take a look on `RouteGenericInterface` yet, but sounds legit
feel free to suggest a PR so I could jump in and push it forward
