### ISSUE TITLE
The latest release 3.0.2 dose not include any changes.

### ISSUE THREAD

**Issue by N1kl8s** [yonathan06/fastify-now#27]
Hello!
      
Firstly, thanks for your work on this project!

The merge request #26  is not included in the latest release 3.0.2.

**Comment by yonathan06** [comment]
@N1kl8s published again under 3.0.4, can you update and try again?

**Comment by millette** [comment]
Odd... <https://github.com/yonathan06/fastify-now/compare/v3.0.2...v3.0.4> indicates changes in `package.json` and `tsconfig.json` but #26 was included [between 3.0.1 and 3.0.2](https://github.com/yonathan06/fastify-now/compare/v3.0.1...v3.0.2).

**Comment by N1kl8s** [comment]
I suspect that this package is manually published to npm and in v3.0.2 was the build either not executed or something went wrong without notice. I tested the new Version 3.0.4 an everything is in place an working.

**Comment by yonathan06** [comment]
You are right, I didn't find the time yet to set up a proper github action for publishing on new tag, and I forgot to build before publish 😅
