### ISSUE TITLE
Declare types on main export

### ISSUE THREAD

**Issue by darvids0n** [yonathan06/fastify-now#30]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `fastify-now@3.0.4` for the project I'm working on.

Defined the types of the default export in a way compatible with TypeScript 5.0 typechecks. No code changes needed, this was enough to fix my type resolution 😄 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/fastify-now/package.json b/node_modules/fastify-now/package.json
index 27fe845..9f76750 100644
--- a/node_modules/fastify-now/package.json
+++ b/node_modules/fastify-now/package.json
@@ -13,7 +13,8 @@
   "exports": {
     ".": {
       "require": "./.build/index.js",
-      "import": "./.build/esm/index.mjs"
+      "import": "./.build/esm/index.mjs",
+      "types": "./.build/esm/index.d.ts"
     }
   },
   "repository": {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by yonathan06** [comment]
updated and published with v3.0.5
