### ISSUE TITLE
vitest benchmark files are not ignored

### ISSUE THREAD

**Issue by tompahoward** [yonathan06/fastify-now#33]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `fastify-now@3.0.5` for the project I'm working on.

We're using vitest on our project and while fastify-now correctly ignores *.test.ts files and *.spec.ts files, it doesn't ignore *.bench.ts files.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/fastify-now/.build/index.js b/node_modules/fastify-now/.build/index.js
index a661262..11f9986 100644
--- a/node_modules/fastify-now/.build/index.js
+++ b/node_modules/fastify-now/.build/index.js
@@ -39,7 +39,7 @@ if (typeScriptEnabled) {
     extensions.push('.ts');
 }
 const isRoute = (ext) => extensions.includes(ext);
-const isTest = (name) => name.endsWith('.test') || name.endsWith('.spec');
+const isTest = (name) => name.endsWith('.test') || name.endsWith('.spec') || name.endsWith('.bench');
 const isDeclaration = (name, ext) => ext === '.ts' && name.endsWith('.d');
 function addRequestHandler(module, method, server, fileRouteServerPath) {
     const handler = module[method];
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by yonathan06** [comment]
Hi, feel free to open a PR with those changes, I will include it in the next release
