### ISSUE TITLE
Dynamic routing on windows system

### ISSUE THREAD

**Issue by web-disciple** [yonathan06/fastify-now#7]
Hello,

**First of all, congratulations I find your plugin brilliant!**

Then I was wondering if there was a solution to the fact that on windows we cannot have filename with any of the following characters: `\ / : * ? " < > | `

There may be a possible alternative that I do not know or a tricks ?

I'm afraid my question is stupid because I'm new to fastify and if it is I apologize in advance.

_good evening_

**Comment by yonathan06** [comment]
We can change it to be `[param]` instead of `:param`
Would you want to open a PR on that?

**Comment by web-disciple** [comment]
Yes i made the change on this PR : https://github.com/yonathan06/fastify-now/pull/8
If you want me to change or improve something about PR don't hesitate ;)

**Comment by TheoryOfNekomata** [comment]
Does this have any movement? I'm having the same issue and it would be nice to get some updates instead of opening another PR so no efforts will be wasted.

Thanks!

**Comment by yonathan06** [comment]
@TheoryOfNekomata I don't see any progress on the PR, feel free to open a PR of your own

**Comment by web-disciple** [comment]
Hello @TheoryOfNekomata, I have not yet found free time to complete the PR. There is not much to do in fact in the PR to be correct, I will not be able to tell you when I will work on it again, but what is certain is that I will end up completing this PR, someday!

**Comment by yonathan06** [comment]
I added support for square brackets in the file names, you can use the new version now `2.3.0`
